apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      environment: qa
  template:
    metadata:
      labels:
        app: nginx
        environment: qa
    spec:
      containers:
      - name: nginx
        image: rohankamble103/nginx:qa
        ports:
        - containerPort: 3000
